title: Modeling Matter(s)
description: Early career researchers illuminate the experiments, tools, and mental models they use to understand the world around us.
baseurl: ""
url: "http://www.modelingmatters.com"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Podcast Feed settings
title:          Modeling Matter(s)
email:          tess@modelingmatters.com
description:    "Early career researchers illuminate the experiments, tools, and mental models they use to understand the world around us."
subtitle:       "Up-and-coming scientists illuminate (why) Modeling Matter(s)."
url:            http://modelingmatters.com/
language:       en-us
author:         ModelingMatter(s)
copyright:      "CC BY 4.0"

feed:
  collections:
    episodes:
      path: "/episodes.xml"

collections:
  episodes:
